
fortune:
  fallbackFortune: Local fortune configuration 
  
security:
  oauth2:
      client:
          clientId: 
          clientSecret: 
          accessTokenUri: 
          grantType: 
            
  
  
    